DROP TABLE IF EXISTS dbinfo CASCADE;
DROP TABLE IF EXISTS session CASCADE;

DROP TYPE IF EXISTS person_role CASCADE;
DROP TABLE IF EXISTS person CASCADE;

DROP TABLE IF EXISTS household CASCADE;

DROP TYPE IF EXISTS household_member_role CASCADE;
DROP TABLE IF EXISTS household_member CASCADE;

DROP TABLE IF EXISTS household_invitation CASCADE;

DROP TABLE IF EXISTS shopping_list CASCADE;

DROP TABLE IF EXISTS shopping_item CASCADE;